### PR TITLE
Quiet compiler warnings for signatures

### PR DESCRIPTION
**Pull request by pprindeville**
There are missing/incomplete function declarations.  Also a missing header.

Signed-off-by: Philip Prindeville <philipp@redfish-solutions.com>

### CODE REVIEW

**Comment by pprindeville** [comment]
I'm the Fedora packaging owner (downstream) for this package, and we've been applying these changes and shipping for a long time (years), in case anyone is wondering if they've been tested...

**Comment by pprindeville** [comment]
BTW, when is 2.3.11 due out?

**Comment by phokz** [comment]
Hi,
thank for PR. What else do you think should be done before version bump?

Best regards
Josef

**Comment by pprindeville** [comment]
> What else do you think should be done before version bump?

Regarding git? Or something else?

**Comment by pprindeville** [comment]
Sorry, thinking of a different PR.

There was one other quick fix I can think of. I’ll send you a PR shortly.

**Pull request merged**
